### ISSUE TITLE
Suggestion: sortable tables

### ISSUE THREAD

**Issue by wchristian** [pjcj/Devel--Cover#159]
In bigger projects it can be useful to be able to sort tables, particularly the file table, by percentages in the files.

This could probably be added fairly easily using http://www.kryogenix.org/code/browser/sorttable/ which has a very permissive license.

**Comment by pjcj** [comment]
This is already implemented in the html_basic report.  I don't really want to implement it in the html_minimal (default) report because I'm not keen on supporting that code.  The plan is to make the html_basic report the default, but there are one or two things which probably need to be tightened up before I do that.

The html_basic report is being used on https://cpancover.com so you can see how it looks there.

So thanks for the the suggestion, but I'm going to close this and try to work on making the html_basic report sufficient to be the default.

**Comment by pjcj** [comment]
Oh, and sorry it took me so long to reply :(

**Comment by wchristian** [comment]
Haha, don't worry. That solution seems perfectly fine to me. :)

Also, https://cpancover.com/ seems down, but http://cpancover.com/ works.

**Comment by pjcj** [comment]
Thanks - looks like I messed up something with the nginx config.  I'll try to get it sorted this weekend.
