### ISSUE TITLE
Uncoverable paths when using experimental signatures

### ISSUE THREAD

**Issue by christopherraa** [pjcj/Devel--Cover#179]
Given the following code:

``` perl
package Foo;
no warnings 'experimental::signatures';
use feature 'signatures';              

sub bar( $self, $baz ) {
  ...
}
```

`Devel::Cover` reports uncovered conditions on the method, namely when checking for the number of arguments passed to the method. It seems that the injected code (from the signatures feature) has some overlap in the intervals for checks on number of arguments. The checks are `unless @_ >= 2` and `unless @_ <= 2`. It will not be possible to get 100% coverage because of this overlap. Here are two screenshots of how it appears in our report:

![2016-11-14-152059_585x81_scrot](https://cloud.githubusercontent.com/assets/924763/20268118/0d2653ae-aa7e-11e6-951c-5aa3fdcbd944.png)
![2016-11-14-152121_548x78_scrot](https://cloud.githubusercontent.com/assets/924763/20268130/1411829c-aa7e-11e6-829e-b70d318205bc.png)

**Comment by Ovid** [comment]
We're also getting bitten with this on our team. We have a very large code base and our test coverage is very good, but we use signatures extensively and would love to know if there is at least a workaround for this.

**Comment by Ovid** [comment]
Also, on the off chance this was not handled because signatures were experimental, in version 26, they're no longer experimental :)

**Comment by pjcj** [comment]
Yes, it wasn't because they were experimental, but because I haven't got around to looking at the problem.  Although I may have been justifying that because they were still experimental.

I suspect what we'll need to do is match the optrees and hack the results somehow.

If anyone wants to get started on this, I'd suggest that approach.

**Comment by Ovid** [comment]
For what it's worth, due to how signatures are handled in 5.26.0, this is no longer an issue. When I switched from 5.24 to 5.26 on a fairly large code base, this problem went away. Our overall code coverage rose 5%, and our branch coverage rose 15% (this is on 87.9% overall coverage). It might be worth merely documenting this as a limitation of "experimental" signatures.

**Comment by pjcj** [comment]
Ah, this is great news.  We need to get a test in place, so if anyone has anything for that please post it.  Otherwise I'll look into it at some point, and I'll leave the ticket open until then.

Thanks all!

**Comment by pjcj** [comment]
I've now (eventually) added this test and so I'm closing this ticket.  Thanks all!
