### ISSUE TITLE
Use of uninitialized value in numeric comparison (<=>) at Devel/Cover/DB.pm line 791.

### ISSUE THREAD

**Issue by exodist** [pjcj/Devel--Cover#190]
I get this warning printed for several screens when using Devel::Cover on one of my current projects.

The warning is printed when I run the `cover` script.

I am attaching the cover_db + t and lib in a zip (github does not like tarballs)
[cover_db.zip](https://github.com/pjcj/Devel--Cover/files/1281964/cover_db.zip)
 so that you can hopefully reproduce and inspect. The command used to generate the cover_db is `perl -Ilib scripts/yath -MDevel::Cover=+ignore,^t/,-silent,1; cover`

Things of note:

My project is an alternative to prove, it forks to run each test instead of spawning a new perl each time. Within the fork it will reset $0, and a ton of other global state,it then executes the test script via 'do'.

**Comment by pjcj** [comment]
Thanks very much for the report.  Unfortunately I have been unable to replicate the problem so far.

Running cover on the cover_db you sent doesn't produce the error for me, and I can't run the code because I can't find Test2::Util::Times to install.

But apart from the warnings, does the Devel::Cover output seem correct otherwise?  If so, I will just quieten the warnings.

But I imagine the forking does have something to do with the problem, yes.

**Comment by exodist** [comment]
Yes, apart from the warning everything looks good

**Comment by exodist** [comment]
Also the missing module can be installed by installing the trials for Test2 and Test2::Suite

**Comment by pjcj** [comment]
Unfortunately I still can't manage to find Test2::Util::Times, even in the trial releases, but I have made a change to handle the case where the start time is undefined and pushed it with 39ee220b1c04c442e1ab9077fea7309e2ebc9769.  If you feel like testing whether that fixes the problem for you I'd be happy to hear back.

But I'm confident, so I have also pushed the Changes file and added you to the Contributors file.  Please feel free to amend or delete your entry there as you see fit.  I'll close the ticket, but please reopen it if the problem is not actually fixed.

Thanks!
