### ISSUE TITLE
branch coverage show "unless" instead of "if"

### ISSUE THREAD

**Issue by szabgab** [pjcj/Devel--Cover#209]
I have this line of code

```
if (not defined $extension or not exists $format{$extension})
```

This is how it is show in the File Coverage. However in the Branch coverage it is shown as

```
unless (defined $extension and exists $format{$extension})
```

in the Condition coverage it is shown as
```
defined $extension and exists $format{$extension}
```

IMHO this change from `if` to `unless` is a bit confusing.

Tried on Devel-Cover-1.29 on https://github.com/szabgab/perl5-markua-parser

**Comment by pjcj** [comment]
The problem here is that I am using B::Deparse to get at just the code of the condition and branch.  B::Deparse is not the easiest of code to work with, and especially not if you are mucking with its internals somewhat, which I am here.  I agree that this is not nice but, unfortunately, I don't know any other way, other than perhaps messing with PPI, which I don't really want to do.

I'm always on the lookout for better solutions here, and I'm open to suggestions, but for now I'm afraid that I'm just going to close this as I can't fix it sensibly.  But thanks very much for taking the time to report it.
