### ISSUE TITLE
Moose-related: BUILD method is not ignored by cover -test

### ISSUE THREAD

**Issue by balajirama** [pjcj/Devel--Cover#233]
I use the coverage report I can get from `Devel::Cover` for my class using `cover -test`. Unfortunately, it generates its own Pod coverage report. Ideally, if there is a `author-pod-coverage.t` test then it should take the Pod coverage report from there. But since cover -test ignores all author tests it is not possible to use it.

If you consider including `author-pod-coverage.t` in your report it is possible to get a clean Pod coverage report with `Dist::Zilla::Plugin::Test::Pod::Coverage::Configurable` which has the also_private option.

**Comment by balajirama** [comment]
I used a work-around for now. Because `Dist::Zilla` creates the build directory and `Makefile` I have to do the following steps. I modified my .travis.yml to do the following instead:

```
dzil test -aall
dzil clean
dzil kwalitee
cd <build-directory>
perl Makefile.PL
HARNESS_PERL_SWITCHES=-MDevel::Cover=-db,cover_db,-coverage,statement,time,branch,condition,subroutine,pod-also_private-BUILD make test
cover -report codecov
```

This works with continuous integration.

But really cover -test should be enhanced. Perhaps this issue category should be changed from a "Bug" to an "Enhancement" to allow users to specify the -coverage pod-also_private-BUILD option in the command-line.

**Comment by pjcj** [comment]
Thanks very much for your report.

`cover -test` is supposed to be a simple command to perform the most common options.  But I appreciate that it is helpful and that it's nice to continue its use in more complicated situations.  I'm not sure I want to add all the coverage options to the `cover`command.  But, the environment variable `$DEVEL_COVER_OPTIONS`is available and it's contents are appended to any other options provided.

Would this be a reasonable solution to your problem?

I'll close the ticket on the assumption that this will solve the problem here but, if not, or I have misunderstood, please reopen it.

Thanks again!
