### ISSUE TITLE
Disabling implicit -blib

### ISSUE THREAD

**Issue by hurricup** [pjcj/Devel--Cover#236]
Is it possible to disable implicit `-blib` option?
I run coverage for tests and want data to be collected from my `lib` directory, not `blib`
But it is exists and looks like I can't turn it off without deleting `blib` directory.

**Comment by pjcj** [comment]
If you use the option -blib,0 then the implicit use of blib when it the directory is there is overridden.  Note that you may then need to suppress the coverage of test files manually.

The blib functionality is used to try to ensure that XS modules are covered correctly, and that the code that is run is that which will be installed.  I think this should be the standard bahaviour, but if you prefer it otherwise the switch is there.

I'll close the ticket but feel free to reopen it if this solution doesn't work.
