### ISSUE TITLE
error in devel::cover when running tests with Multi threading in our CI

### ISSUE THREAD

**Issue by mormoti** [pjcj/Devel--Cover#265]
Hi all,
we will be happy if you can help us to solve the following issue:
we saw that issue should solved between versions 1.27-1.33 here
https://github.com/pjcj/Devel--Cover/commit/28071439f283b2c64ed8f3001523ff85c60e364a

according to this commit we upgraded our version from 1.22 to 1.28 we are still getting the following error that causing our CI to fail.

error msg:

Devel::Cover: Warning: can't open .fa/hook for MD5 digest: No such file or directory
Can't read /tmp/test_cover/digests with JSON: unexpected end of string while parsing JSON string, at character offset 4096 (before "(end of string)") at /opt/moti/perl5/lib/perl5/x86_64-linux-thread-multi/Devel/Cover/DB/IO/JSON.pm line 43, <$fh> chunk 1.
BEGIN failed--compilation aborted at /usr/share/fa/bin/ckp2urt line 2.

thanks a lot!

**Comment by pjcj** [comment]
Hello,

My suspicion is that you are using an existing coverage DB with the new version.  In particular you are parsing with JSON where it has been written in another format.

Perhaps the easiest way of dealing with this is to remove the old DB and start again from scratch.

Otherwise, take a look at the DEVEL_COVER_DB_FORMAT environment variable in the documentation for how to specify the serialisation format you are using.
