### ISSUE TITLE
Issue with multiple Perl interpretors

### ISSUE THREAD

**Issue by vijaykumar3333** [pjcj/Devel--Cover#266]
Hi,
I have 2 versions of Perl (5.10 and 5.16) installed on my linux machine. Devel Cover is built with Perl 5.10.
I am using environment variables to get code coverage. We have a single process that invokes 5.10 Perl files and also 5.16 Perl files in its code path execution.

setenv PERL5OPT -MDevel::Cover=-db,/tmp/cover_db,-ignore,^ade/
setenv PERL5LIB /usr/local/lib64/perl5

**We run into the error below and the program breaks :**
_This version of Devel::Cover was built with Perl version 5.010001.
It is now being run with Perl version 5.016003.
Attempting to make adjustments, but you may find that some of your modules do not have coverage data collected.  You may need to alter the +-inc, +-ignore and +-select options.
Can't load '//scratch/ext_src/perl_cover/5.10.1/lib/site_perl/5.10.1/x86_64-linux//auto/Devel/Cover/Cover.so' for module Devel::Cover: //scratch/ext_src/perl_cover/5.10.1/lib/site_perl/5.10.1/x86_64-linux//auto/Devel/Cover/Cover.so: undefined symbol: PL_stack_sp at /usr/lib64/perl5/DynaLoader.pm line 190.
at **/ade/varamand_ecs20191023/cstest/macro/run_ecs_srg.pl** line 0.
BEGIN failed--compilation aborted._

I don't want the coverage for run_ecs_srg.pl file that uses Perl 5.16 modules. Ignore option is not working when I try to exclude the complete directory "/ade/" in PERL5OPT  env variable like below: 
setenv PERL5OPT -MDevel::Cover=-db,/tmp/cover_db,-ignore,^ade/

How do I ensure that Perl files that are built with 5.16 are excluded from code coverage, so that I don't run into the error above? Because my Perl-Devel is built with 5.10.

**Comment by pjcj** [comment]
Hello,

I can't quite work out your setup, but if you are running Perl 5.16 with Devel::Cover turned on you'll need to ensure that you are picking up the libraries for 5.16.  If you don't care about coverage for your code run with 5.16 then you could also unset $PERL5OPT for that section though I understand this would probably be invasive.

The way you are trying with -ignore won't work, I'm afraid, because it is Devel::Cover itself which interprets that -ignore and so has to be loaded first, and that's where you are hitting the problem.

I'll close this ticket because I don't think there is anything I can do on the coverage side, I think you're going to need to manage the environment variables specially in your somewhat special environment.
