### ISSUE TITLE
PPI::HTML syntax highlighting (html_basic) is not splitting lines correctly

### ISSUE THREAD

**Issue by Kencho** [pjcj/Devel--Cover#270]
When using the reporter `html_basic`, if `PPI::HTML` is installed, its code highlighting will not split the lines correctly (the report table shows the whole code as a single line, with no statistics extracted for it). The `Perl::Tidy` highlighting implementation works correctly.

Tested with:
- `Devel::Cover` 1.36
- `PPI::HTML` 1.08
- `Perl::Tidy` 20200110

**Comment by jkahrman** [comment]
This was caused by https://github.com/pjcj/Devel--Cover/commit/f6ac4196ab0d369190a5eabf7ee6e34e14510656. When the whitespace of Devel::Cover::Reporter::Html_basic was cleaned up, whitespace was added to the token used in the 'split' calls below it. The PPI::HTML document is no longer parsed correctly. 

Removing the spaces between the word 'class' and the '=' in the $split string fixes the issue.
