### ISSUE TITLE
Optionally include in reports files that aren't touched at all by tests

### ISSUE THREAD

**Issue by DrHyde** [pjcj/Devel--Cover#43]
My test suite is so bad that some modules in my project aren't just badly covered, they're not touched at all. And so they don't show up in reports from Devel::Cover. I'd like to have them show up.

Something like this would be nice:

$ cover -select_dir lib

to force it to report on every .pm file under the lib/ directory.

**Comment by pjcj** [comment]
Since I've not got to any solution for this over a number of years, even though I have needed a solution, I think it's fair to say that I'm unlikely to build anything into Devel::Cover to handle this condition.

The way I have managed this so far is to have one test which just loads all possible modules.  This has value as a test in itself, and also ensures that every module is included in the coverage report.

So I'm going to close this ticket with the recommendation of using this workaround.

thanks all!

**Comment by dboehmer** [comment]
I’m working on a project with some CGI scripts. Only parts of the code are wrapped nicely in .pm modules. We want to use global code coverage as a metric for project improvement.

`use` is only an option for modules which a safe to use. I’d love to see an option to add a .pm or .pl file to the cover database without running it. I think compiling it for getting statements, branches, etc. is probably necessary and should be fine.

The suggestions posted here don’t apply to .pl files which do some actions when executed.

**Comment by DrHyde** [comment]
Thanks!
